### ISSUE TITLE
Login captcha not working [v25.5.1]

### ISSUE THREAD

**Issue by tesfabpel** [flathub/io.itch.itch#17]
During the log in, after you enter your email and password, the Captcha screen remains fully black.
It seems like there is a webview inside it but it doesn't render somehow...

**Comment by heldderarbeit** [comment]
I can confirm this issue is still present. A temporary solution is to start itch with the "--no-sandbox" parameter once, e.g. 
`flatpak run io.itch.itch --no-sandbox` (see: https://github.com/itchio/itch/issues/2863#issuecomment-1709453334)

It's not necessary anymore after you have solved the captcha.

Sadly the latest stable version for the itch.io client is still stuck on v25.1.1 from May 12, 2021. We only had canary (read: bleeding-edge) releases since then.

**Comment by Doomsdayrs** [comment]
With 4364700fa62def61b537ecca8b0f8235982057d8 I added the latest release which was 4 hours ago now.

**Comment by heldderarbeit** [comment]
Thanks Login is working again, I think this issue can be closed.
